Feature/temp logger
easyflow-chat/easyflow-backend pull request #10
Opened 2024-06-16 20:59 UTC by Fabbboy

2024-06-16 21:01 UTC, Fabbboy commented
need your opinion @Dragon437619

2024-06-17 05:37 UTC, Dragon437619 requested changes
Es paar logs müest mwh no apasse

2024-06-17 05:37 UTC, Dragon437619 commented on src/api/auth/auth.service.go
> +		logger.PrintfInfo("User with id: %s not found", payload.UserId)
Nid rather PrintfError

2024-06-17 05:37 UTC, Dragon437619 commented on src/api/chat/chat.controller.go
> +		logger.PrintfError("Error getting chat by id: %s", err.Details)
Wird hie d id usgäh

2024-06-17 05:37 UTC, Dragon437619 commented on src/api/chat/chat.service.go
> +				logger.Printf("Error getting last message for chat with id: %s. Error: %s", chatUserKey.ChatId, err.Error())
PrinfError

2024-06-17 05:37 UTC, Dragon437619 commented on src/api/chat/chat.service.go
> +		logger.Printf("Error getting chat with id: %s. Error: %s", chatId, err)
PrintfError

2024-06-17 05:37 UTC, Dragon437619 commented on src/api/chat/chat.service.go
> +		logger.Printf("Error getting chat user key for chat with id: %s. Error: %s", chatId, err)
PrintfError

2024-06-17 05:37 UTC, Dragon437619 commented on src/api/chat/chat.service.go
> +		logger.Printf("Error getting messages for chat with id: %s. Error: %s", chatId, err)
PrintfError

2024-06-17 05:37 UTC, Dragon437619 commented on src/api/chat/chat.service.go
> +			logger.Printf("Error getting user with id: %s. Error: %s", chatUserKey.UserId, err)
PrintfError

2024-06-17 05:37 UTC, Dragon437619 commented on src/api/user/user.service.go
> +		logger.Printf("User with email: %s already exists", payload.Email)
PrintfError right

2024-06-17 05:44 UTC, Fabbboy commented on src/api/auth/auth.service.go
> +		logger.PrintfInfo("User with id: %s not found", payload.UserId)
I don't thnk it's an error when a user is not found it does nut put our backend applictaion in a critical state where we need to fix something

2024-06-17 05:46 UTC, Fabbboy commented on src/api/chat/chat.controller.go
> +		logger.PrintfError("Error getting chat by id: %s", err.Details)
Nope xD das isch eh Fähler vo mir aber ebe mir sötte über alli err's drüber goh und err.Details setze

2024-06-17 05:47 UTC, Dragon437619 commented on src/api/auth/auth.service.go
> +		logger.PrintfInfo("User with id: %s not found", payload.UserId)
Okay then we leave it

2024-06-17 05:50 UTC, Fabbboy commented on src/api/chat/chat.service.go
> +				logger.Printf("Error getting last message for chat with id: %s. Error: %s", chatUserKey.ChatId, err.Error())
Ich weiss nit öp mir do en Error throwe sötte oder halt nit. Im sinne vo, dass d möglichkeit existiert, dass es kie lsat message git den nit aber wenn die möglichkeit nit existiere söt den würdi PritnfError mache

2024-06-17 05:55 UTC, Fabbboy commented on src/api/chat/chat.service.go
> +		logger.Printf("Error getting chat with id: %s. Error: %s", chatId, err)
en error gits halt au wenn dr chat nit gfunde worde isch ka wieso das throwed aber wenn halt kein chat mit dere id gfunde wird gits en error und find eig nit, dass das en error isch

2024-06-17 05:55 UTC, Fabbboy commented on src/api/chat/chat.service.go
> +		logger.Printf("Error getting chat user key for chat with id: %s. Error: %s", chatId, err)
same do

2024-06-17 05:56 UTC, Fabbboy commented on src/api/chat/chat.service.go
> +		logger.Printf("Error getting messages for chat with id: %s. Error: %s", chatId, err)
au do wenn dr chat nit gfunde wird returned das en error dorum solabg mir uns nit sicher sin , dass unseri api miss used wird könne mir nit devo usgpoh dass es eh maraidb issue git

2024-06-17 05:56 UTC, Fabbboy commented on src/api/user/user.service.go
> +		logger.Printf("User with email: %s already exists", payload.Email)
Bringt unseri application nit in en kritische state dorum würdi nei sage

2024-06-17 07:17 UTC, merged