feat(endpoint-setup): created helper function which gets all the depe…
easyflow-chat/easyflow-backend pull request #15
Opened 2024-06-20 19:02 UTC by Dragon437619

Creates a function which gets all the necesarry stuff for an endpoint and retunrns it.

2024-06-20 19:12 UTC, Fabbboy requested changes
Please rework the error handling and split up the helper function and reapply for checking

2024-06-20 19:12 UTC, Fabbboy commented on src/common/utils.go
> +		panic("[User] Logger not found in context")
user? the module should be specified

2024-06-20 19:12 UTC, Fabbboy commented on src/common/utils.go
> +		panic("[User] Type assertion to *common.Logger failed")
same here

2024-06-20 19:12 UTC, Fabbboy commented on src/common/utils.go
> +// PS: This function is not the preetiest but it gets the job done
needs a helper function to check for non existing values this would make the code cleaner

2024-06-20 19:12 UTC, Fabbboy commented on src/common/utils.go
> +// and return the payload, logger, db, and config
sure but i would be more Developer friendly if you would return errors that happened so we can manually handle them like we want. I would say this would be more intelligent than just retuning a bool for success

2024-06-20 19:12 UTC, Fabbboy commented on src/database/model.go
> +	Email          string         `gorm:"type:varchar(255);uniqueIndex"`
is this true? did you check?

2024-06-20 19:12 UTC, Fabbboy commented on src/database/model.go
> +	Email          string         `gorm:"type:varchar(255);uniqueIndex"`
could be i dont know

2024-06-20 19:12 UTC, Fabbboy commented on src/common/utils.go
> +// SetupEndpoint is a helper function to setup the endpoint with the necessary dependencies
think about how we could break uip this function in multiple smaler its more managable and scalable also we could multithread it which makes it a lot faster. As a read once:
a function should not be longer than 15-20 lines of code and should not do more than one task
dont take it serious but think about how we could break up into smaller parts. feel free to create a "endpoint.go" file or smt in /api/ where we have some more room

2024-06-20 19:12 UTC, Fabbboy commented on src/api/auth/auth.controller.go
>  		return
return? i dont like this i would like to see the actual stuff that gets returned its more approachable and can be easily changed also we still dont have rebose error reporting and this would make it even harder. we would have to supply many parameters jsut to get a simple return working. If possible take some of the error handling from the setupEndpoint and handle them in the controller you may also just collect all errors that happen and return a []error so we can inter and report all fo them

2024-06-20 19:12 UTC, Fabbboy commented on src/api/auth/auth.controller.go
>  		return
same here

2024-06-20 19:20 UTC, Dragon437619 commented on src/common/utils.go
> +		panic("[User] Logger not found in context")
Good point

2024-06-20 19:22 UTC, Dragon437619 commented on src/database/model.go
> +	Email          string         `gorm:"type:varchar(255);uniqueIndex"`
Yes it wasn't right before and i am not sure if it is working now actually i will test

2024-06-21 06:43 UTC, Fabbboy approved these changes

2024-06-21 06:43 UTC, Fabbboy approved these changes

2024-06-21 06:44 UTC, Fabbboy submitted a review, later dismissed

2024-06-21 10:36 UTC, Fabbboy approved these changes

2024-06-21 10:42 UTC, merged